### ISSUE TITLE
BRIDGE_CONNECTION_ERROR

### ISSUE THREAD

**Issue by YutoUchimi** [YutoUchimi/sesame_ros#9]
When I launched sesame_server and called `~get_status`, the output parameter `responsive` was False.
```
$ roscore
```
```
$ rosrun sesame_ros sesame_server.py _auth_token:=<my_auth_token> _nickname:=<my_sesame>
```
```
$ rosservice call /sesame_server/get_status
nickname: <my_sesame>
serial: XXXXXXXXXXXX
device_id: XXXXXXXX-XXXX-XXXX-XXXXXXXXXXXX
battery: 100
locked: True
responsive: False
```

So I tried calling `~force_sync`, but the command failed because of `BRIDGE_CONNECTION_ERROR`.
```
$ rosservice call /sesame_server/force_sync
status: terminated
successful: False
error: BRIDGE_CONNECTION_ERROR
```

How can I solve this?

**Comment by YutoUchimi** [comment]
Please make sure your Wi-fi module is correctly set.
- Check if electric power can be supplied to it.
- Check if it is close enough to your Sesame.

**Comment by YutoUchimi** [comment]
Electric power had not been supplied!
Thank you!

**Comment by YutoUchimi** [comment]
Old software version of Wi-fi module may cause this `BRIDGE_CONNECTION_ERROR`.
If this error occurs and 2 check points shown above seems good, please connect your smart phone with your Sesame using smartphone application via bluetooth, and then update the software to the newest version.

**Comment by nmssalman** [comment]
everything is fine, but getting the same error when im trying with the api with node.js. even the lock is working with the mobile app.
